server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    loadbalancer:
      ribbon:
        enabled: true
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
    discovery:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
