spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            config-server:
              - uri: http://localhost:8888
            discovery-server:
              - uri: http://localhost:8761