eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # Desativa registro (é o próprio servidor)
    fetch-registry: false       # Não busca outros serviços
    service-url:
      defaultZone: http://localhost:8761/eureka
